name: "Demo using GitHub cache for 3D models w/GitHub Actions"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'pcb/*.kicad_sch'
      - 'pcb/*.kicad_pcb'
      - 'configs/*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot_gha.yml'
  pull_request:
    paths:
      - 'pcb/*.kicad_sch'
      - 'pcb/*.kicad_pcb'
      - 'configs/*.kibot.yaml'
      - 'Makefile'
      - '.github/workflows/kibot_gha.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  KiCost:
    name: Render PCB
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (only last code)
      uses: actions/checkout@v3

    - name: Cache 3D models data
      id: models-cache
      uses: set-soft/cache@main
      with:
        path: ~/cache_3d
        key: cache_3d

    - name: Run KiBot
      # full k6 + dev
      # You can also use v2_k6
      #uses: INTI-CMNB/KiBot@v2_dk6
      uses: INTI-CMNB/KiBot@21f51904fea704ffe13e98bc819be80ee6a1fae1
      with:
        config: configs/blender_export.kibot.yaml
        dir: Generated
        board: pcb/light_control.kicad_pcb
        cache3D: YES

    - name: Retrieve results
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: All_Outputs
        path: Generated
